<?php

namespace App\Widgets;

/**
 *  |--------------------------------------------------------------------------
 *  |   You can use the below snippets to override the defaults.
 *  |====== Remove this doc block if you don't need it ========
 *  |--------------------------------------------------------------------------
 *  | public $contextAs = '$data'; (default : '$data')
 *  | public $controller = '\App\ClassPath\ُSomeClass@someMethod'; (optional)
 *  | public $presenter = \App\ClassPath\WidgetPresenter::class; (optional)
 *  | public $minifyOutput = true; (use it to override the default value in config file)
 *  | public $cacheTags = []; (optional) (Available for all cache driver)
 *  | public $cacheLifeTime = 0;   (use it to override the default value in config file)
 *  | public $cacheView = false; You may only cache the controller result. (default : true)
 *  | public $template; (optional) (By default it looks for the view file generated by artisan)
 *  |--------------------------------------------------------------------------
 */
class InvoiceStatus
{
    public const STATUS=[
        0=>"CANCLE",
        1=>"PAID",
        2=>"PENDING",
    ];

    private function description($key)
    {
        return [
            "PAID" => "پرداخت شده",
            "CANCLE" => "پرداخت نشده",
            "PENDING" => "در حال پرداخت",
        ][$key];
    }
    private function classType($key)
    {
        return [
            0 => "danger",
            1 => "success",
            2 => "warning",
        ][$key];
    }
    public function getDescription($key)
    {
        return $this->description($key);
    }


    public  function getTag($key)
    {
        return "<span class='badge badge-".$this->classType($key)."'>".$this->description(self::STATUS[$key])."</span>";

    }
    public function data($a, $b)
    {
        return [];
    }
    /**
     * If the widget output depends on query strings you should return key names.
     * otherwise you get undesired results out of the cache store. for example:
     * example.com/product?page=1 and you use the page number in your db query
     * or if you want it to be separated for each user: return auth()->id();
     */
    public function extraCacheKeyDependency($args)
    {
        return [/* request('page') */];
    }
}
